# Generated by Django 3.1.3 on 2020-12-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0003_wronganswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millionaire_app.questions')),
            ],
        ),
        migrations.RemoveField(
            model_name='wronganswers',
            name='question',
        ),
        migrations.DeleteModel(
            name='CorrectAnswers',
        ),
        migrations.DeleteModel(
            name='WrongAnswers',
        ),
    ]
