# Generated by Django 3.1.3 on 2020-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0004_auto_20201201_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=255),
        ),
    ]
