# Generated by Django 3.1.3 on 2020-12-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0005_auto_20201201_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['id']},
        ),
    ]
