# Generated by Django 3.1.3 on 2020-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0006_auto_20201201_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
