# Generated by Django 3.1.3 on 2020-12-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0007_questions_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='status',
            new_name='used_question',
        ),
    ]
