# Generated by Django 3.1.4 on 2020-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0008_auto_20201201_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='true_answer',
            field=models.BooleanField(default=False),
        ),
    ]
