# Generated by Django 3.1.4 on 2020-12-02 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0009_answers_true_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='point',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
