# Generated by Django 3.1.4 on 2020-12-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire_app', '0013_scores_has_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'ordering': ['-score']},
        ),
        migrations.RemoveField(
            model_name='scores',
            name='has_finished',
        ),
    ]
